steps:
  - uses: actions/checkout@v4

  - name: Set working directory
    run: cd app

  - name: Install dependencies
    working-directory: app
    run: npm install

  - name: Build
    working-directory: app
    run: npm run build

  - name: Deploy
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: TechHistory/app/dist